config/routes.rb
Rails.application.routes.draw do
  resources :equations
  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/equation.rb
class Equation < ActiveRecord::Base

  belongs_to :user, counter_cache: true

  before_save :evaluate_response, if: :start_at_changed?
  after_update :update_user_score

  SCORES = {
    correct: 2,
    incorrect: -2,
    forfeit: -1
  }

  MAX_INT   = 12
  MIN_INT   = 0
  MAX_DELTA = 5

  Operations = {
    0 => '+',
    1 => '-'
  }

  def initialize
    super
    self.a = rand(MAX_INT)
    self.b = rand(MAX_INT)
    self.op = operation(a,b)

    self.result = eval("#{a}#{op}#{b}")

    self.delta1 = rand(MAX_DELTA + 1)
    self.delta2 = rand(MAX_DELTA - 1)
    while delta1 == delta2
      self.delta2 = rand(MAX_DELTA)
    end
  end

  def operation(a,b)
    if a > b
      Equation::Operations[rand(100) % 2]
    else
      '+'
    end
  end

  def options
    @options ||= [
      result,
      eval("#{result}#{operation(a,b)}#{delta1}"),
      eval("#{result}#{operation(a,b)}#{delta2}")
    ].shuffle
  end

  def response_score
    SCORES[response_grade]
  end

  def op_class
    op == '-' ? :danger : :success
  end

  def op_text
    op == '-' ? :minus : :plus
  end

  def response_time
    (finish_at - start_at).to_f
  end

  private

  def evaluate_response
    update_column(:is_correct, response == result)
  end

  def update_user_score
    user.update_score(response_score, response_grade) unless user.nil?
  end

  def response_grade
    return :forfeit if response.nil?
    is_correct ? :correct : :incorrect
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  has_many :equations

  def set_default_role
    self.role ||= :user
  end

  def update_score(equation_score, response_grade)
    puts "update_score(#{equation_score}, #{response_grade})"
    new_score = score + equation_score
    new_score = 0 if new_score < 0
    update_column(:score, new_score)
    increment("#{response_grade}_count".to_sym)
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/equations_controller.rb
class EquationsController < ApplicationController

  # before_action :authenticate_user!

  def new
    flash[:info] = "You're using <em>Algebro</em> as a <strong>guest</strong>: Sign in or Sign up to keep your score! Also, make sure your <b>volume</b> is up!".html_safe unless user_signed_in?
    @equation = Equation.new
    @equation.save
  end

  def update
    @equation = Equation.find(params[:id])
    @equation.update(equation_params.merge({
      user_id: user_signed_in? ? current_user.id : nil,
      finish_at: Time.now,
      solve_time: (equation_params['solve_time'].to_f * 50)
      }))
    redirect_to equation_path(@equation)
  end

  def show
    flash[:info] = "You're using <em>Algebro</em> as a <strong>guest</strong>: Sign in or Sign up to keep your score! Also, make sure your <b>volume</b> is up!".html_safe unless user_signed_in?
    @equation = Equation.find(params[:id])
  end

  private

  def equation_params
    params.require(:equation).permit(:id, :response, :start_at, :solve_time)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/equations_helper.rb
module EquationsHelper
end

app/views/equations/new.html.erb
<%= form_for @equation do |e| %>
<section>
  <div class="container">
    <!-- /.row -->
    <div class="row">
      <div class="col-xs-12 text-center">
        <%= e.hidden_field :solve_time, value: 0 %>
        <span class="badge">
          <i class="fa fa-clock-o fa-3"></i> <span class='timer'>0</span>
        </span>
      </div>
    </div>
    <!-- /.row -->
    <div class="row">
      <div class="col-xs-12 text-center">
        <span class="label finger label-primary hide-ing reveal-able speak-able timer-on">READY!</span>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 text-center reveal">
        <span data-text='<%= @equation.a %>' class="label finger label-primary speak "><%= @equation.a %></span>
        <span data-text='<%= @equation.op_text %>' class="label finger label-<%= @equation.op_class %> speak "><%= @equation.op %></span>
        <span data-text='<%= @equation.b %>' class="label finger label-primary speak "><%= @equation.b %></span>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 text-center reveal">
        <span data-value="<%= (value = @equation.options.pop) %>" data-text="<%= value == @equation.result ? 'Correct!' : 'Incorrect...' %> <%= "#{@equation.a} #{@equation.op_text} #{@equation.b} is #{@equation.result}" %>" class="finger label label-info fade-ing timer-off submit-response speak-ing"><%= value %></span>
        <span data-value="<%= (value = @equation.options.pop) %>" data-text="<%= value == @equation.result ? 'Correct!' : 'Incorrect...' %> <%= "#{@equation.a} #{@equation.op_text} #{@equation.b} is #{@equation.result}" %>" class="finger label label-info fade-ing timer-off submit-response speak-ing"><%= value %></span>
        <span data-value="<%= (value = @equation.options.pop) %>" data-text="<%= value == @equation.result ? 'Correct!' : 'Incorrect...' %> <%= "#{@equation.a} #{@equation.op_text} #{@equation.b} is #{@equation.result}" %>" class="finger label label-info fade-ing timer-off submit-response speak-ing"><%= value %></span>
      </div>
    </div>
    <!-- /.row -->



  </div>
  <!-- /.container -->
  <%= e.hidden_field :response %>
  <%= e.hidden_field :start_at, value: Time.now %>
</section>
<% end  %>

app/views/equations/show.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 text-center">
        <span class="badge">
          <i class="fa fa-clock-o fa-3"></i> <%= number_with_precision(@equation.solve_time * 0.001, precision: 2) %>
        </span>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 text-center">
        <span  class="label finger small label-primary"><%= @equation.a %></span>
        <span  class="label finger small label-default"><%= @equation.op %></span>
        <span  class="label finger small label-primary"><%= @equation.b %></span>
        <span  class="label finger small label-default">=</span>
        <span  class="label finger small label-success"><%= @equation.result %></span>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 text-center">
        &nbsp;
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 text-center prize">
        <% if @equation.is_correct %>
        <i class="fa fa-plus-square ruby fa-3"></i>
        <% @equation.response_score.times do %>
        <i class="fa fa-diamond ruby fa-3"></i>
        <% end %>
        <% else %>
        <i class="fa fa-minus-square gray fa-3"></i>
        <% @equation.response_score.abs.times do %>
        <i class="fa fa-diamond gray fa-3"></i>
        <% end %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 text-center">
        &nbsp;
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 text-center">
        <%= link_to "<i class=\"fa fa-chevron-circle-right fa-9 fade-ing\"></i>".html_safe, new_equation_path %>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%
     alert_type = case name.to_s
     when 'info'
       'info'
     when 'warn'
       'warning'
     when 'error'
       'danger'
     when 'success'
       'success'
     else
       'info'
     end
    %>
    <div class="alert alert-<%= alert_type %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "<i class='fa fa-tree'></i>".html_safe, root_path, class: 'navbar-brand' %>
      <%= link_to "<i class='fa fa-plus-circle gray'></i> #{current_user.equations_count.to_i}".html_safe, root_path, class: 'visible-xs pull-right navbar-brand' if user_signed_in? %>
      <%= link_to "<i class='fa fa-diamond ruby'></i> #{current_user.score.to_i}".html_safe, root_path, class: 'visible-xs pull-right navbar-brand' if user_signed_in? %>
      <%= link_to "<i class='fa fa-heart gray'></i> #{current_user.name}".html_safe, root_path, class: 'visible-xs pull-right navbar-brand' if user_signed_in? %>

    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <% if user_signed_in? %>
      <ul class="nav navbar-nav pull-right">
        <li>
          <%= link_to "<i class='fa fa-heart gray'></i> #{current_user.name}".html_safe, root_path, class: 'navbar-brand' %>
        </li>
        <li>
          <%= link_to "<i class='fa fa-diamond ruby'></i> #{current_user.score.to_i}".html_safe, root_path, class: 'navbar-brand' %>
        </li>
        <li>
          <%= link_to "<i class='fa fa-plus-circle gray'></i> #{current_user.equations_count.to_i}".html_safe, root_path, class: 'navbar-brand' %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to "<i class='fa fa-question-circle'></i>".html_safe, page_path('about') %></li>
<% if user_signed_in? %>
  <li><%= link_to "<i class='fa fa-pencil'></i>".html_safe, edit_user_registration_path %></li>
  <li><%= link_to "<i class='fa fa-times'></i>".html_safe, destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Admin', '/admin' %></li>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Algebro" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "A minimalist playground for first grade algebra" %>">
  <link href='https://fonts.googleapis.com/css?family=Ubuntu+Mono:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render 'layouts/navigation' %>
  </header>
  <%= render 'layouts/messages' %>
  <%= yield %>
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <p>
            <%= link_to "algebro&trade; is open source".html_safe, 'https://gitlab.com/etozzato/algebro' %>
            by <%= link_to "Mek", 'https://twitter.com/mekdigital' %>
          </p>
        </div>
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container -->
  </footer>
</body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<section>
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h1><i class='fa fa-question-circle'></i> About this web::application</h1>
        <p>
          I wanted to help my kids to practice algebra.. So I <em>gamified</em> the process.<br>
          Gamification is the concept of applying game mechanics and game design techniques to engage and motivate people to achieve their goals.
        </p>
        <h3>Get ready, start the timer:</h3>
        <%= image_tag('ready.png', class:'img-thumbnail') %>

        <h3>Receive an equation! What's seven + eight? Tap on the correct answer.</h3>
        <%= image_tag('question.png', class:'img-thumbnail') %>

        <h3>You clicked sixteen, and it's not correct. You have lost two gems. Try another!</h3>
        <%= image_tag('answer.png', class:'img-thumbnail') %>

      </div>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->
</section>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<section>
  <div class="container">
    <!-- /.row -->
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>"A minimalist playground for first grade algebra" <%= link_to "<i class='fa fa-question-circle'></i>".html_safe, page_path('about') %></h1>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 text-center">
        <br><br>
        <% if user_signed_in? %>
        <span class="speak" data-text="Hello, <%= current_user.name %>!"></span>
        <% end %>
        <%= link_to "<i  class=\"fa fa-chevron-circle-right fa-9 fade-ing speak-able\"></i>".html_safe, new_equation_path %>
      </div>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->
</section>